
#ifndef STATES_H
#define STATES_H

#include <wallet.h>

extern char global_slot_display[MAX_SLOTS + 1][SLOT_DISPLAY_LEN];

typedef enum {
    STATE_SPLASH,
    STATE_SLOT_SELECTION,
    STATE_GEN_TYPE_SELECTION,
    STATE_WORD_ENTRY,
    STATE_CONFIRM_EXIT,
    STATE_RANDOM_WORD_TEST,
    STATE_GENERATE_ADDRESS,
    STATE_BONKTIME_GAME,
    STATE_BONKTIME_ENTROPY,
    STATE_SHOW_GENERATED_WORDS,
    STATE_CONFIRM_GENERATED_WORDS,
    STATE_SAVE_WALLET,
    STATE_IDLE,
    STATE_DEBUG,
    STATE_WALLET_MENU,
    STATE_SET_PIN,
    STATE_ENTER_PIN
} AppState;

#endif
